// MARK: Change Log
/***************************************************************************************************************************************
 
 VIPLoungeRouter.swift
 VIPLounge
 
 This file was generated by the Clean Swift Xcode Templates so you can apply clean architecture to your iOS and Mac projects,
 see http://clean-swift.com
 
 
 4/24/18 <sdm>
 • Initial Code
 
 ***************************************************************************************************************************************/

import Cocoa



// MARK: -
/*====================================================================================================================================*/

@objc protocol VIPLoungeRoutingLogic {
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)

}



// MARK: -
/*====================================================================================================================================*/

protocol VIPLoungeDataPassing {
    
    var dataStore: VIPLoungeDataStore? { get }

}



// MARK: -
/*====================================================================================================================================*/

class VIPLoungeRouter: NSObject, VIPLoungeRoutingLogic, VIPLoungeDataPassing {

    weak var viewer: VIPLoungeViewer?
    var dataStore: VIPLoungeDataStore?

    
    // MARK: - Routing
    /*====================================================================================================================================*/

//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//
//        if let segue = segue {
//
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//
//        } else {
//
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewer!, destination: destinationVC)
//
//        }
//    }
    
    
    // MARK: - Navigation
    /*====================================================================================================================================*/

//    func navigateToSomewhere(source: VIPLoungeViewer, destination: SomewhereViewController) {
//
//      source.show(destination, sender: nil)
//
//    }
    
    
    // MARK: - Passing data
    /*====================================================================================================================================*/

//    func passDataToSomewhere(source: VIPLoungeDataStore, destination: inout SomewhereDataStore) {
//
//      destination.name = source.name
//
//    }
}



//
//
// Public Domain, 2018 by Steve Marcotte
//
// Notwithstanding the foregoing, you may not use, copy, modify, merge, publish, distribute, sublicense, create a derivative work,
// and/or sell copies of the Software in any work that is designed, intended, or marketed for pedagogical or instructional purposes
// related to programming, coding, application development, or information technology.  Permission for such use, copying, modification,
// merger, publication, distribution, sublicensing, creation of derivative works, or sale is expressly withheld.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

